# Generated by Django 5.0.1 on 2024-10-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={
                "ordering": ["is_local", "name"],
                "permissions": [["can_export", "Can export data"]],
                "verbose_name_plural": "currencies",
            },
        ),
        migrations.AddField(
            model_name="currency",
            name="fraction_name",
            field=models.CharField(
                default="قرش", max_length=20, verbose_name="fraction name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="currency",
            name="short_name",
            field=models.CharField(
                default="قرش", max_length=10, verbose_name="short name"
            ),
            preserve_default=False,
        ),
    ]
