# Generated by Django 5.0.1 on 2024-09-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nationalities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nationality",
            name="is_foreign",
        ),
        migrations.AddField(
            model_name="nationality",
            name="is_local",
            field=models.BooleanField(
                default=False, help_text="is it local?", verbose_name="is local"
            ),
        ),
    ]
