# Generated by Django 5.0 on 2024-09-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nationalities", "0002_remove_nationality_is_foreign_nationality_is_local"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nationality",
            name="is_local",
            field=models.BooleanField(
                default=False,
                help_text="is it local or foreign?",
                verbose_name="is local",
            ),
        ),
    ]
