# Generated by Django 5.0.1 on 2024-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0003_alter_position_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["order", "name"],
                "permissions": [["can_export", "Can export data"]],
            },
        ),
        migrations.AddField(
            model_name="position",
            name="order",
            field=models.IntegerField(
                default=1, help_text="order of position", verbose_name="order"
            ),
        ),
    ]
