# Generated by Django 5.0.1 on 2024-09-22 06:06

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cost_centers", "0002_alter_costcenter_options_costcenter_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                4,
                                "name of the faculty should not be less than 4 characters.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "department_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="if you leave it blank, it will be filled based on parent id serial.",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", "department id must be numbers only"
                            )
                        ],
                    ),
                ),
                (
                    "search",
                    models.GeneratedField(
                        db_persist=False,
                        expression=django.db.models.functions.text.Concat(
                            models.F("department_id"),
                            models.Value(" "),
                            models.F("name"),
                            models.Value(" "),
                            models.F("department_id"),
                            models.Value(" "),
                            models.F("name"),
                        ),
                        output_field=models.CharField(max_length=255),
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "cost_center",
                    models.ForeignKey(
                        help_text="the cost center which belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="cost_centers.costcenter",
                        verbose_name="cost center",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        help_text="parent department if exists.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department_id"],
                "permissions": [["can_export", "Can export data"]],
            },
        ),
    ]
