# Generated by Django 5.0.1 on 2024-09-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"permissions": [["can_export", "Can export data"]]},
        ),
    ]
