# Generated by Django 5.0 on 2024-09-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_department_department_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="department id",
            new_name="department_id",
        ),
    ]
