# Generated by Django 5.0 on 2024-09-13 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_rename_department_id_department_department_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["department_id"],
                "permissions": [["can_export", "Can export data"]],
            },
        ),
        migrations.AlterField(
            model_name="department",
            name="department_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "department id must be numbers only"
                    )
                ],
            ),
        ),
    ]
