# Generated by Django 5.0.1 on 2024-10-21 12:37

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("currencies", "0002_alter_currency_options_currency_fraction_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_rate", models.DecimalField(decimal_places=8, max_digits=12)),
                ("is_inverse", models.BooleanField(default=False)),
                (
                    "rate",
                    models.GeneratedField(
                        db_persist=False,
                        expression=models.Case(
                            models.When(
                                models.Q(("is_inverse__exact", True)),
                                then=django.db.models.expressions.CombinedExpression(
                                    models.Value(1), "/", models.F("input_rate")
                                ),
                            ),
                            default=models.F("input_rate"),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=8, max_digits=12
                        ),
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "bulletin_number",
                    models.CharField(
                        help_text="bulletin number from central bank",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(default="", max_length=1000)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "currency__name"],
                "permissions": [["can_export", "Can export data"]],
                "unique_together": {("currency", "date")},
            },
        ),
    ]
