# Generated by Django 5.0.1 on 2024-10-22 10:09
# from pathlib import Path

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_rate", models.DecimalField(decimal_places=8, max_digits=20)),
                ("is_inverse", models.BooleanField(default=False)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=20)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "bulletin_number",
                    models.CharField(
                        help_text="bulletin number from central bank",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", max_length=1000)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "currency__name"],
                "permissions": [["can_export", "Can export data"]],
                "unique_together": {("currency", "date")},
            },
        ),
    ]
