# Generated by Django 5.0.1 on 2024-10-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="input_rate",
            field=models.DecimalField(decimal_places=8, max_digits=28),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="notes",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
