# Generated by Django 5.0.1 on 2024-10-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_rates", "0001_initial_squashed_0005_exchangerate_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="rate",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
