# Generated by Django 5.0.1 on 2024-10-15 20:22

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nationalities", "0004_alter_nationality_name"),
        ("school_types", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                4,
                                "name of the object should not be less than 4 characters.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "search",
                    models.GeneratedField(
                        db_persist=False,
                        expression=django.db.models.functions.text.Concat(
                            models.F("name"), models.Value(" "), models.F("name")
                        ),
                        output_field=models.CharField(max_length=255),
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        help_text="nationality",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools",
                        to="nationalities.nationality",
                        verbose_name="nationality",
                    ),
                ),
                (
                    "school_type",
                    models.ForeignKey(
                        help_text="school type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools",
                        to="school_types.schooltype",
                        verbose_name="school type",
                    ),
                ),
            ],
            options={
                "ordering": ["school_type", "nationality__is_local", "name"],
                "permissions": [["can_export", "Can export data"]],
            },
        ),
    ]
