# Generated by Django 5.0 on 2024-08-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={
                "ordering": ["name"],
                "permissions": [["can_export", "Can export data"]],
                "verbose_name_plural": "faculties",
            },
        ),
    ]
