# Generated by Django 5.0.1 on 2024-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="mobile",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="phone",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
