# Generated by Django 5.0.1 on 2024-09-30 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_email_notes_alter_mobile_notes_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="email",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="mobile",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="mobile",
            name="mobile",
            field=models.CharField(
                help_text="mobile number must be like 0947302503",
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^09\\d{8}$", "mobile number must be like 0947302503"
                    )
                ],
                verbose_name="mobile",
            ),
        ),
    ]
