# Generated by Django 5.0.1 on 2024-10-09 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_email_unique_together_and_more"),
        ("statuses", "0002_alter_status_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["status", "department__department_id", "firstname"]},
        ),
        migrations.RemoveField(
            model_name="employee",
            name="job_status",
        ),
        migrations.AddField(
            model_name="employee",
            name="current_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="religion",
            field=models.CharField(
                choices=[
                    ("M", "Muslim"),
                    ("C", "Christian"),
                    ("J", "Jewish"),
                    ("O", "Other"),
                ],
                default="M",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="statuses.status",
            ),
        ),
    ]
