# Generated by Django 5.0.1 on 2024-10-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0004_alter_employee_options_remove_employee_job_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": [
                    "-status__has_salary",
                    "department__department_id",
                    "job_subtype__job_type",
                    "job_subtype",
                    "firstname",
                ]
            },
        ),
    ]
