# Generated by Django 5.0.1 on 2024-10-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educational_degrees", "0001_initial"),
        ("employees", "0005_alter_employee_options"),
        ("schools", "0001_initial"),
        ("specializations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="graduation_date"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1, help_text="order of position", verbose_name="order"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="is it current?",
                        verbose_name="is current",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", max_length=1000, verbose_name="notes"
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="education_transactions",
                        to="educational_degrees.educationaldegree",
                        verbose_name="education degree",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="education_transactions",
                        to="employees.employee",
                        verbose_name="employee",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="education_transactions",
                        to="schools.school",
                        verbose_name="school",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="education_transactions",
                        to="specializations.specialization",
                        verbose_name="specialization",
                    ),
                ),
            ],
            options={
                "ordering": ["employee__firstname", "order"],
                "permissions": [["can_export", "Can export data"]],
                "unique_together": {("employee", "order")},
            },
        ),
    ]
