# Generated by Django 5.0.1 on 2024-10-21 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employeeproxy_alter_employee_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_type",
            field=models.CharField(
                choices=[("F", "Fulltime"), ("P", "Parttime")],
                default="F",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="ownership",
            field=models.CharField(
                choices=[("O", "Owned"), ("L", "Loaned")], default="O", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
