# Generated by Django 5.0.1 on 2024-10-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_alter_contract_contract_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeProxy",
        ),
    ]
