# Generated by Django 5.0.1 on 2024-10-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_delete_employeeproxy"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="groups.group"
            ),
        ),
    ]
