# Generated by Django 5.0.1 on 2024-10-23 11:47

import apps.currencies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
        ("employees", "0010_employee_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="currency",
            field=models.ForeignKey(
                default=apps.currencies.models.Currency.get_default_pk,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="currencies.currency",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="local_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
