# Generated by Django 5.0.1 on 2024-09-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-created_at", "type"],
                "verbose_name_plural": "activities",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("other", "Other"),
                ],
                default="create",
                max_length=255,
            ),
        ),
    ]
