# Generated by Django 5.0.1 on 2024-09-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_activity_options_alter_activity_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="new_data",
        ),
    ]
