# Generated by Django 5.0.1 on 2024-10-03 13:01

import apps.base.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_remove_activity_new_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="old_data",
            field=models.JSONField(
                blank=True, encoder=apps.base.encoders.CustomJSONEncoder, null=True
            ),
        ),
    ]
