# Generated by Django 5.0 on 2024-09-18 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                4,
                                "name of the faculty should not be less than 4 characters.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="city",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="areas",
                        to="cities.city",
                        verbose_name="city",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [["can_export", "Can export data"]],
            },
        ),
    ]
