# Generated by Django 5.0.1 on 2024-09-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0002_area_search"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["city__name", "name"],
                "permissions": [["can_export", "Can export data"]],
            },
        ),
    ]
